const stores=[
[152,'广东省佛山市南海区九江镇沙头昊盟产业园便利店',22.83428,112.98824],[153,'广东省佛山市顺德区丰华北路盈信街便利店',22.89323,113.07511],[154,'广东省佛山市顺德区乐从镇聚丰国际便利店',22.94809,113.10252],[155,'广东省佛山市顺德区乐从镇劳村市场便利店',22.93405,113.13120],[156,'广东省广州市番禺区市桥光明北路鸿禧华庭便利店',22.95200,113.35631],[184,'广东省佛山市高明区更合镇白石便利店',22.80942,112.56584],[185,'广东省佛山市高明区荷城街道华盈广场便利店',22.88986,112.88434],[186,'广东省佛山市高明区荷城街道金鱼街苏棠村便利店',22.90353,112.87978],[187,'广东省佛山市南海区西樵北江大堤江山一品便利店',22.96554,112.98715],[214,'广东省广州市荔湾区百花路保利花海湾便利店',23.09309,113.21796],[215,'广东省广州市番禺区南村镇广地花园便利店',23.02251,113.33218],[216,'广东省广州市荔湾区花地大道碧桂园朝花便利店',23.07030,113.22787],[217,'广东省广州市番禺区南村镇雅居乐剑桥郡瀚澜一街便利店',23.00576,113.37481],[245,'广东省佛山市南海区大沥镇红星路便利店',23.11685,113.09368],[246,'广东省佛山市南海区大沥镇联安产业园便利店',23.09205,113.15832],[247,'广东省佛山市南海区大沥镇钟边村建发三堂院便利店',23.09695,113.10781],[248,'广东省广州市白云区金沙洲宏词街便利店',23.16732,113.19646],[276,'广东省佛山市禅城区南庄镇保利翠雅花园便利店',22.98577,113.00127],[277,'广东省佛山市南海区狮山广场政协路便利店',23.12679,113.00545],[278,'广东省佛山市南海区狮山镇朗沙社区下罗沙村便利店',23.04112,113.04259],[279,'广东省佛山市南海区狮山镇万荟时代便利店',23.13140,112.99877],[280,'广东省佛山市南海区长华国际商业中心公寓便利店',23.12028,112.99422]];
const plans=[
{date:'9月7日',area:'九江 → 顺德 → 乐从 → 番禺',ids:[152,153,154,155,156]},
{date:'9月8日',area:'更合 → 荷城 → 西樵',ids:[184,185,186,187]},
{date:'9月9日',area:'荔湾 → 南村',ids:[214,216,215,217]},
{date:'9月10日',area:'大沥 → 金沙洲',ids:[245,247,246,248]},
{date:'9月11日',area:'南庄 → 罗村 → 狮山',ids:[276,278,277,279,280]}];
const get=id=>stores.find(s=>s[0]===id);const query=s=>'零食有鸣 '+s[1];const dateFor=id=>plans.find(p=>p.ids.includes(id))?.date||'';
let activeDay=0,overviewMap,overviewLayer,dayMap,overviewFilter='all';let checked=new Set();try{checked=new Set(JSON.parse(localStorage.getItem('youming-checks-v1')||'[]'))}catch(e){}
function amap(s){return 'https://uri.amap.com/search?'+new URLSearchParams({keyword:query(s),city:s[1].includes('广州市')?'广州市':'佛山市',view:'map',src:'youming-routes',callnative:'1'})}
function dayurl(list){const start=list[0],end=list.at(-1),[startLat,startLng]=gcj(start[3],start[2]),[endLat,endLng]=gcj(end[3],end[2]);return 'https://uri.amap.com/navigation?'+new URLSearchParams({from:`${startLng},${startLat},${shortName(start)}`,to:`${endLng},${endLat},${shortName(end)}`,mode:'car',policy:'1',src:'youming-routes',callnative:'1'})}
function shortName(s){return s[1].replace(/^广东省(?:佛山市|广州市)/,'').replace(/便利店$/,'')}
function outOfChina(lng,lat){return lng<72.004||lng>137.8347||lat<0.8293||lat>55.8271}
function transformLat(x,y){return -100+2*x+3*y+.2*y*y+.1*x*y+.2*Math.sqrt(Math.abs(x))+(20*Math.sin(6*x*Math.PI)+20*Math.sin(2*x*Math.PI))*2/3+(20*Math.sin(y*Math.PI)+40*Math.sin(y/3*Math.PI))*2/3+(160*Math.sin(y/12*Math.PI)+320*Math.sin(y*Math.PI/30))*2/3}
function transformLng(x,y){return 300+x+2*y+.1*x*x+.1*x*y+.1*Math.sqrt(Math.abs(x))+(20*Math.sin(6*x*Math.PI)+20*Math.sin(2*x*Math.PI))*2/3+(20*Math.sin(x*Math.PI)+40*Math.sin(x/3*Math.PI))*2/3+(150*Math.sin(x/12*Math.PI)+300*Math.sin(x/30*Math.PI))*2/3}
function gcj(lng,lat){if(outOfChina(lng,lat))return [lat,lng];const a=6378245,ee=.00669342162296594323,dLat=transformLat(lng-105,lat-35),dLng=transformLng(lng-105,lat-35),rad=lat/180*Math.PI,magic=1-ee*Math.sin(rad)**2,sqrt=Math.sqrt(magic);return [lat+dLat*180/((a*(1-ee))/(magic*sqrt)*Math.PI),lng+dLng*180/(a/sqrt*Math.cos(rad)*Math.PI)]}
function markerIcon(s){const done=checked.has(s[0]);return L.divIcon({className:'',html:`<div class="map-marker ${done?'complete':'pending'}"><span>${s[0]}</span></div>`,iconSize:[28,28],iconAnchor:[14,28],popupAnchor:[0,-27]})}
function popupHtml(s){const done=checked.has(s[0]);return `<div class="popup-title">${shortName(s)}店</div><div class="popup-date">${dateFor(s[0])} · ${done?'已检查':'未检查'}</div><div class="popup-actions"><button class="check-action" onclick="toggleChecked(${s[0]})">${done?'改为未检查':'标记已检查'}</button><a target="_blank" rel="noopener" href="${amap(s)}">高德导航</a></div>`}
function renderOverviewMarkers(fit=false){if(!overviewMap)return;overviewLayer.clearLayers();const visible=stores.filter(s=>overviewFilter==='all'||!checked.has(s[0]));visible.forEach(s=>L.marker(gcj(s[3],s[2]),{icon:markerIcon(s),title:shortName(s)}).bindPopup(popupHtml(s)).bindTooltip(`${dateFor(s[0])} · ${shortName(s)}`).addTo(overviewLayer));if(fit&&visible.length)overviewMap.fitBounds(visible.map(s=>gcj(s[3],s[2])),{padding:[24,24]})}
function renderOverviewList(){const visible=stores.filter(s=>overviewFilter==='all'||!checked.has(s[0]));document.getElementById('overview-list').innerHTML=visible.map(s=>`<button type="button" class="status-item ${checked.has(s[0])?'done':''}" onclick="toggleChecked(${s[0]})"><i></i><span><b>${shortName(s)}</b><small>${dateFor(s[0])} · ${checked.has(s[0])?'已检查':'未检查'}</small></span></button>`).join('')||'<p class="mapnote">全部门店已检查完成。</p>'}
function renderProgress(){const count=checked.size;document.getElementById('checked-count').textContent=`${count} / ${stores.length}`;document.getElementById('progress-bar').style.width=`${count/stores.length*100}%`;renderDayNav()}
function toggleChecked(id){checked.has(id)?checked.delete(id):checked.add(id);localStorage.setItem('youming-checks-v1',JSON.stringify([...checked]));renderProgress();renderOverviewMarkers(false);renderOverviewList();render(activeDay)}window.toggleChecked=toggleChecked;
function initOverview(){if(typeof L==='undefined'){document.getElementById('all-map').innerHTML='<p class="mapnote">总览地图暂时无法加载，可使用下方门店列表记录检查状态。</p>';renderOverviewList();return}overviewMap=L.map('all-map',{zoomControl:true}).setView([23.01,113.05],10);L.tileLayer('https://webrd0{s}.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=7&x={x}&y={y}&z={z}',{subdomains:'1234',maxZoom:18,attribution:'高德地图'}).addTo(overviewMap);overviewLayer=L.layerGroup().addTo(overviewMap);renderOverviewMarkers(true)}
function initDayMap(list){if(typeof L==='undefined'){document.getElementById('day-map').innerHTML='<p class="mapnote">当天地图暂时无法加载，请使用下方高德导航。</p>';return}const points=list.map(s=>gcj(s[3],s[2]));dayMap=L.map('day-map',{zoomControl:true});L.tileLayer('https://webrd0{s}.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=7&x={x}&y={y}&z={z}',{subdomains:'1234',maxZoom:18,attribution:'高德地图'}).addTo(dayMap);L.polyline(points,{color:'#cf3b2f',weight:4,opacity:.85}).addTo(dayMap);list.forEach(s=>L.marker(gcj(s[3],s[2]),{icon:markerIcon(s),title:shortName(s)}).bindPopup(popupHtml(s)).addTo(dayMap));dayMap.fitBounds(points,{padding:[24,24]})}
function renderDayNav(){document.getElementById('days').innerHTML=plans.map((p,i)=>{const n=p.ids.filter(id=>checked.has(id)).length;return `<button type="button" data-day="${i}" class="${i===activeDay?'active':''}">${p.date}<span>${n}/${p.ids.length} 已检查</span></button>`}).join('')}
function render(n){activeDay=n;const p=plans[n],list=p.ids.map(get);if(dayMap){dayMap.remove();dayMap=null}document.querySelectorAll('nav button').forEach((b,i)=>{b.classList.toggle('active',i===n);b.setAttribute('aria-pressed',i===n)});document.getElementById('content').innerHTML=`<div class="routehead"><h2>${p.date} · 当天路线</h2><span>${list.filter(s=>checked.has(s[0])).length}/${list.length} 已检查</span></div><div class="fastest"><b>建议最快顺序</b><span>${p.area}</span><p>按门店所在片区由近到远排列，尽量减少跨区折返；当天从路线任一端附近出发时，可按地图实际路况选择正向或反向行驶。</p></div><details open><summary>${p.date} 路径图<small>展开 / 收起</small></summary><div class="mapwrap"><div id="day-map" role="img" aria-label="${p.date}高德到店路径图"></div><div class="mapnote">高德底图显示当天门店和建议顺序连线，行驶道路与实时耗时以高德导航结果为准。</div></div></details><div class="actions"><a class="btn primary" target="_blank" rel="noopener" href="${dayurl(list)}">↗ 高德打开首站至末站路线</a><a class="btn" target="_blank" rel="noopener" href="${amap(list[0])}">高德导航第1站</a></div><ol class="route-strip" aria-label="${p.date}到店顺序">${list.map((s,i)=>`<li><a href="#store-${s[0]}"><b>${i+1}</b>${shortName(s)}</a></li>`).join('')}</ol><div class="stores">${list.map((s,i)=>{const done=checked.has(s[0]);return `<article class="store ${done?'checked-store':''}" id="store-${s[0]}"><div class="top"><span class="stop">${p.date} · 第${i+1}站</span><span class="id">${done?'✓ 已检查':'○ 未检查'}</span></div><h3><a target="_blank" rel="noopener" href="${amap(s)}">${shortName(s)}店 ↗</a></h3><div class="address">${s[1]}</div><div class="actions"><button type="button" class="btn check-btn ${done?'done':''}" onclick="toggleChecked(${s[0]})">${done?'✓ 已检查':'标记已检查'}</button><a class="btn primary" target="_blank" rel="noopener" href="${amap(s)}">高德导航</a></div></article>`}).join('')}</div>`;initDayMap(list)}
document.getElementById('days').addEventListener('click',e=>{const b=e.target.closest('button');if(b)render(Number(b.dataset.day))});document.getElementById('show-all').onclick=()=>{overviewFilter='all';document.getElementById('show-all').classList.add('active-filter');document.getElementById('show-unchecked').classList.remove('active-filter');renderOverviewMarkers(true);renderOverviewList()};document.getElementById('show-unchecked').onclick=()=>{overviewFilter='unchecked';document.getElementById('show-unchecked').classList.add('active-filter');document.getElementById('show-all').classList.remove('active-filter');renderOverviewMarkers(true);renderOverviewList()};
function theme(){const hour=new Date().getHours(),dark=hour<7||hour>=19;document.body.classList.toggle('dark',dark);document.getElementById('theme').textContent=dark?'☾ 夜间 · 自动':'☀ 日间 · 自动'}theme();setInterval(theme,60000);renderProgress();initOverview();render(0);
